### ISSUE TITLE
Create Skeleton File for this CSC Sparse Matrix Class

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f20-Lab06#11]
This issue is about creating the header and source file for the CSC sparse matrix class.

Some tasks in this issue:
* Create the header file
* Create the source file
* Define all attributes
* Create all methods as empty operations.
* Create a unit test executable for this class.

**Definition of Done**
The source file, header file, and unit test main are added to the repository in the correct location.

**Comment by bkochuna** [comment]
Ugh... this issue description is terrible! It looks like it just got copied from #13 and others!

It should be noted that #14, #15, #16, and #18 all depend on this ticket.

**Comment by mhig-umich** [comment]
<img width="727" alt="Screen Shot 2020-10-25 at 4 32 53 PM" src="https://user-images.githubusercontent.com/53484799/97122015-e2970c00-16df-11eb-8a0b-7a453d7e7e75.png">

**Comment by mhig-umich** [comment]
This is what I have so far. My biggest question is how does the template class differ when it is a child class and there are inheritances? I'm not sure where to go with that.

**Comment by peareric** [comment]
@mhig-umich I received a notification for this because I was at one point assigned. For some general background on inheritance and templating, there are a lot of great websites (and some bad ones). I find that the GeeksForGeeks posts on [inheritance](https://www.geeksforgeeks.org/inheritance-in-c/), [ploymorphism](https://www.geeksforgeeks.org/polymorphism-in-c/), and [templating](https://www.geeksforgeeks.org/templates-cpp/) are all useful. Syntax as well as concepts are covered for all topics.

**Comment by bkochuna** [comment]
@peareric thanks for posting the links. 

@mhig-umich I'm not sure if you're question is just generally about inheritance with classes, templating, or how templating works with inheritance.

Regarding the first, irrespective of templating, the methods and attributes defined on the base class are usable by the child class (provided that you use public inheritance). So you can reuse the same constructor, destructor, and setCoefficient methods. When there is a template parameter involved I assume it behaves similarly. I would expect that sublcasses of a templated base class would have to use the template parameter in the same way as the base class (but I'm not certain about this).

If you missed lab Friday, watch the last ~20 min or so where we talk about what is needed for the subclass implementations.

**Comment by peareric** [comment]
@mhig-umich @bkochuna A small note: classes derived from a templated base class do not need to be templated themselves, i.e. something like
```
class Derived : Public TemplatedBase<double> { ...
```
is valid. Of course, a templated derived class is valid as well.

**Comment by deanrp2** [comment]
I just wrote the .hpp/.cpp/CMakeLists.txt/test files such that they are similar to the ones @knbarton created for the CSR format. I am getting an error when I try to do the cmake->make->ctest, but I think this should be an improvement to what was in the repo when I pulled it (I think). I just want the structure here to be similar because I am supposed to be making the methods for CSR and CSC so it will be much easier for me if my code is the same between the two.
