### ISSUE TITLE
Create Skeleton File for this COO Sparse Matrix Class

### ISSUE THREAD

**Issue by knbarton** [bkochuna/ners570f20-Lab06#17]
This issue is about creating the header and source file for the COO sparse matrix class.

Some tasks in this issue:

- Create the header file
- Create the source file
- Define all attributes
- Create all methods as empty operations.
- Create a unit test executable for this class.

**Definition of Done**
The source file, header file, and unit test main are added to the repository in the correct location.

**Comment by bkochuna** [comment]
@knbarton Good first ticket. Right in line with #13.

Note that the following tickets depend on this ticket:
#20, #27, #29, #30

**Comment by bkochuna** [comment]
@Tcw7468 will work on this

**Comment by Tcw7468** [comment]
> @Tcw7468 will work on this

I have changed assignments and am  no longer working on this.

**Comment by hpleei** [comment]
Just made a PR for this. Please review my works and let me know if it is good to be merged in.
Link for the PR: https://github.com/bkochuna/ners570f20-Lab06/pull/50

**Comment by mduschenes** [comment]
Upon further review (after pull request was accepted), I think the printMatrix and set/get coefficient methods in this child COO class are not necessary, due to being implemented in the parent SparseMatrix Class. I commented them out for now in the coosparsemat.hpp but we can always put them back in.

Similarly, commented out the overloaded COOSparseMatrix constructor, taking 3 arguments for the row/col idx and the coo matrix array. Just to simplify things for now, and keep things consistent with the parent class constructor arguments, but we could always add in this functionality afterwards.
