### ISSUE TITLE
Implement Methods on COO Sparse Matrix Class

### ISSUE THREAD

**Issue by hpleei** [bkochuna/ners570f20-Lab06#29]

**Comment by bkochuna** [comment]
This issue needs a description. I recommend the following which is similar to my recommendation for #34.
> This issue is about implementing the functional code for the CSR class independent of the associated unit test.
> It will involve implementing those methods not defined on `SparseMatrix` class or overloading them.
> It will also involve adding the attributes for the specific storage format.
>
> This issue will depend on #17.
>
> **Definition of Done:**
> This issue is complete when the unit test defined in #20 is passing.

**Comment by bkochuna** [comment]
@Tcw7468 will work on this.

**Comment by Tcw7468** [comment]
> @Tcw7468 will work on this.

I have changed assignments and am  no longer working on this.

**Comment by mduschenes** [comment]
@peareric Likely syntax errors in methods in src/coo/coosparsemat.cpp for class definitions and use of shared pointer vec_ptr type for result of SpMV ?

**Comment by mduschenes** [comment]
@peareric Wasn't sure on what flow you think is best for the allocation of the row/col/matrix arrays in _assembleStorage_ and then the deallocation in the __unAssemble_ ? 

For _assembleStorage_ right now am ensuring the matrix is in the building or assembled state, then if in the assembled state, will clear the row/col/matrix arrays through _unAssemble,_ and will then fill these arrays with the existing data from __buildCoeff_. The matrix state is then set as assembled. This means if the _assembleStorage_ is called more than once, the _setCoeffecient_ calls aren't cumulative throughout the existance of the class object existance, but only since the last call to assemble the matrix. 

For _unAssemble_, it is checked that the matrix is in the assembled state, and then clears the row/col/matrix arrays, and sets the state as building.

**Comment by peareric** [comment]
Closed via #64
